version: 0.0
os: linux
files:
  - source: /
    destination: /var/python/{GitHubProjectName}
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 5
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
