class ValidationErrorTypes:
    def __init__(self):
        pass

    TYPE_ERROR = 'TYPE_ERROR'
    LENGTH_ERROR = 'LENGTH_ERROR'
    NOT_TESTABLE = 'NOT_TESTABLE_ERROR'
    NOT_LENGTH_TESTABLE = 'NOT_LENGTH_TESTABLE'
    INVALID_LIST_ITEMS = 'INVALID_LIST_ITEMS'
    NOT_ITERABLE = 'NOT_ITERABLE'
    REQUIRED = 'REQUIRED'
